#### Bayesian Methodology and Inferential Applications to Public Policy

#### By Ritika Iyer



### Bayesian Methodology in Public Policy:
Bayesian regression can be a particularly interesting method to use to address public policy issues because of its ability to take into account prior information about the parameters of interest. Many policy problems are multi-faceted and evolve over time - as such, a single policy data set is unlikely to be representative of all relevant information to the question at hand. Additionally, most policy solutions have nuance and may work differently across contexts. This dependence on context makes it hard to simply rely on point estimates as a meaningful way to design policy. For this reason, Bayesian methods that allow for the estimation of a posterior distribution, rather than a point estimate, can offer more to policymakers in terms of projected impact of a policy option. 

Since results from Bayesian models are presented in probabilistic terms, many find that they are more applicable to answering public policy questions than frequentist results that use irrelevant cutoff values and provide very particular insights. Bayesian results are typically viewed as easier to interpret and apply for policymakers because they shed light on the probability of impact that one variable will have on their outcome of interest (Holzwart et al., 2018). This allows policymakers and social scientists to more effectively and holistically quantify their uncertainty associated with a particular policy option, not limited to just the uncertainty from sampling itself. Appropriate calculation of risks is very important in decision making, especially when the impacts of decisions are nation-wide. For this reason alone, Bayesian techniques are often preferred to frequentist methods in the public policy arena. 

Another aspect of Bayesian methodology that make it particularly useful in social policy research and evaluation is its ability to incorporate existing information as priors, to strengthen the model’s conclusions, and also use new data to inform the conclusions in real-time (Holzwart et al., 2018). This feature can be especially relevant to assessing the impacts of a pilot social services program – researchers and policymakers could leverage priors for parameters from their performance in related public programs, as well as use conclusions from the model to improve the pilot program in areas that it is lacking (for example, addressing desired outcomes, better targeting, reduced complexity). 

There are a few challenges with Bayesian methodologies that may hinder application to public policy. Given that Bayesian results are probabilistic, they often lead to a “grey area” in terms of determining the right policy conclusions. Though this does allow for flexibility in interpretation and perhaps can be more closely aligned with the nuances of real-world policy issues, it can also make it very difficult to translate results to actual and concrete policy decisions (Holzwart et al., 2018). Additionally, calculations of Bayesian results are very computationally-intensive, which can be a major issue for policy making at the local level where budgets are potentially more constrained, resources (both in terms of human and physical processing capital) are scarce, and time is spread out over multiple priorities. Finally, selecting appropriate priors to inform the Bayesian model and posterior distribution requires extensive thought and can be challenging for many researchers (Holzwart et al., 2018). Though these prior assumptions in the policy space are often subjective, they should be rooted in facts as much as possible based on historical information, which can be difficult to reasonably parse out. Overall, these various limitations can make the application and interpretation of Bayesian methodologies impractical for certain contexts in the public arena. 

#### Applications of Bayesian Frameworks to Public Policy Problems
There are many potential applications of Bayesian statistical methods in the public policy space. During the neo-Bayesian revival in the 1950s, Bayesian methods were considered to be inappropriate to use in solving public problems involving government and policy contexts because of the importance of prior distributions (Fienberg, 2011). However, as computers for statistical calculations were introduced in the 1960s and potential applications of Bayesian models increased as a result, researchers have argued that Bayesian methods can be very useful and applicable to public policy problems. This transition was aided by the 1990s introduction of Markov Chain Monte Carlo (MCMC) methods that allow for sampling from the posterior distribution (Fienberg, 2011). 

Some researchers, like Stephen Fienberg, have worked extensively to make the case that utilizing priors and likelihood functions can benefit policymakers in program design and evaluation (Fienberg, 2011). One historical application of Bayesian methods in the public domain is election night forecasting, first used in the United States in the 1960s (Fienberg, 2011). These methods have been used to predict election results in other countries as well, including the U.K. (Brown et al., 1997). 

Another interesting application of Bayesian methodology is in the pharmaceutical testing and regulation space, particularly used to aid the U.S. Food and Drug Administration (FDA) in bringing medical drugs and devices to the global market. Given that the clinical trial process is often lengthy, Bayesian methods have been touted as being able to speed up the information access and dissemination process for ongoing clinical trials, as compared to frequentist methods (Fienberg, 2011). In addition to improving the efficiency of clinical trials reviewed by the FDA, Bayesian methods can also improve the way that drugs and devices are evaluated by incorporating a diverse range of information as priors in the assessment process, including experimental studies, patient testimonials, observational data, and qualitative data from doctors and scientists. Bayesian techniques also offer more flexibility to the FDA and researchers, particularly in identifying issues with patient welfare upfront and allowing for modifications to the study based on them (Fienberg, 2011). Ultimately, this adaptive framework improves patient outcomes and allows for more confidence in the FDA’s drug approval process. Other relevant applications of Bayesian methodologies in the public policy space include modeling outcomes and implications of climate change (Schneider, 2002), and estimating the presence of disabilities in the elderly community in the U.S. (Fienberg, 2011). 

Outside of government, many research organizations and universities have applied Bayesian techniques to address public policy problems. The Centers for Medicare and Medicaid Services (CMS) worked with RTI and RAND on two projects related to risk tolerance, program evaluation, and provider performance (Freeman et al., 2017; Paddock, 2017). At the University of Wisconsin, researchers used multiple Bayesian models to improve estimates of reading proficiency scores for international students (Kaplan, 2017). Using data on employment for low-income adults, researchers from Mathematica Policy Research used priors from past related studies to reach probabilistic conclusions (using thresholds) on the impacts of employment programs (Vollmer et al., 2017). Finally, Columbia University researcher Andrew Gelman used Bayesian analysis to better understand why there are red states and blue states, distinguished by political party support, in the U.S. In this application, Bayesian techniques allowed for the multi-level modeling to consider both geographic and demographic variables across the population – this helps understand the conundrum that while richer people are more likely to support Republican candidates and poorer people are more likely to vote for Democratic candidates, richer states on the country’s coasts usually support Democrats and, similarly, low-income areas in the center of the U.S. geographically generally lean Republican (Gelman, 2014). 

Across applications in social science and policy research, probabilistic results from Bayesian methods are often more useful for policy decisions. If a frequentist evaluation of a policy finds no statistically significant effect of the program, it is possible that the Bayesian results could conclude that there is a specific numerical chance that the impact of the program is at least at a certain value, in the units of measurement for the metric at hand (Holzwart et al., 2018). This nuanced framework allows decision makers with flexibility to decide how much program success is suitable to their needs and identify which aspects are not operating as expected. These results also give room to conduct a stronger and more robust cost-benefit analysis, an important aspect of policy analysis. 

