#### Bayesian Methodology and Inferential Applications to Public Policy

#### By Ritika Iyer



### Conclusions:
This paper started with an introduction to Bayesian thinking, explaining the two main advantages of using a Bayesian methodology for linear regression: the use of priors to inform the model, as well as a probabilistic estimation in the form of a posterior distribution. These benefits of Bayesian regression methods make it a particularly useful framework for policymakers, whom may find it difficult to rely on point estimates from frequentist models to inform policy decisions. These and other differences between Bayesian and frequentist models were discussed at length, along with examples of when and how Bayesian methods can be used to solve important issues in the public domain. The application component of this paper examined the impact of child health outcomes, like BMI, on education performance, measured by test scores, for children in India. We find that there is a positive relationship between the two variables of interest - higher BMIs are generally associated with better test performance in children. We get similar estimates for both Bayesian and frequentist methodologies, even when the sample size is dramatically reduced. However, we do see that a smaller sample size makes our coefficients lose statistical significance, have larger errors, and more variation in the chain sampling. 

From a policy perspective, particularly in the international development context, sample size is important because data quality can be difficult to manage but does play a significant role in the quality of analysis generated for decision making. If moving forward with a Bayesian methodology despite a relatively small sample size, researchers should put significant though into selecting informative priors rather than relying on defaults. This is also important, because as sample size decreases, Bayesian results rely increasingly on the priors. Not all inferential questions will be best answered by Bayesian thinking, but many can be. In thinking about how to address development challenges globally, probabilistic estimates are likely to be much more relevant and useful than point estimates that lack nuance. There is incredible potential for policymakers worldwide to adopt Bayesian techniques to improve, expand, and inform public programs. 

