#### Bayesian Methodology and Inferential Applications to Public Policy

#### By Ritika Iyer



### Introduction:
This paper will introduce Bayesian methodology as a way of answering inferential questions in the public policy space. It will start by giving an overview of linear regression, covering both frequentist and Bayesian frameworks. The next sections will compare and contrast frequentist and Bayesian models, drawing extensively from the literature to discuss the benefits and shortcomings of each type. I then hope to make the case as to why Bayesian methodology is particularly useful and relevant to informing public policy decisions, as compared to other methodologies. I provide real-world examples of Bayesian applications in the public domain from government, research organizations, and universities. The final section of this paper applies Bayesian inferential analysis to a simple policy question in the international development space. This analysis uses childhood poverty data from eastern India to understand the relationship between child health status (measured by Body Mass Index, or BMI) and academic performance (measured by test scores). The application component of this paper includes descriptive statistics, Bayesian inference and Markov Chain Monte Carlo sampling methodology, posterior distribution checks and inferential analysis. It ends with a comparison of results from the Bayesian methodology versus a frequentist methodology across different sample sizes. 

Regression methods are useful for estimating a relationship between two variables, x and y. Here, we treat x as the independent variable that has an estimated impact, measured through the regression method, on our dependent or outcome variable y. In bivariate regression models, x and y are the only relevant variables included, an the estimated impact of x on y is found in the 'coefficient' on the x-term. Equation 1 below shows an example of a bivariate model between x and y, where b is the coefficient that tells us the estimated impact of an increase in x on y (Koehrsen, 2018). The error term, e, represents all other effects of variables that are not listed in the model.

y = a + b(x) + e     (1)

However, bivariate models are most often subject to omitted variable bias, an issue that arises when additional variables that have an impact on y are not included in the model. Omitted variable bias results in a biased coefficient on x, or a biased b estimate. For this reason, multivariate models that include several x's rather than just the one of interest are generally preferred. 

In frequentist models of linear regression, like the one showed above, we are able to obtain point estimates of the relationship of interest. This paper will focus on another type of regression, Bayesian linear regression. The Bayesian method of regression estimates probability distributions rather than point estimates (Clyde et al., 2020). Using a similar framework introduced in Equation 1 above, the Bayesian linear regression model estimates a distribution of outcomes for the output y sampled from a normal distribution of the x's included (Koehrsen, 2018). 